# Generated by Django 4.2.7 on 2024-03-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_comments_market_prod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='market_prod',
            name='owner',
        ),
        migrations.AddField(
            model_name='market_prod',
            name='duration',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
